### ISSUE TITLE
`ember-let` in `dependencies` of add-on causes build failure

### ISSUE THREAD

**Issue by cafreeman** [thefrontside/ember-let#28]
### Ember Version / Ember CLI Version:

**Ember Version:** 2.8.0
**Ember CLI Version:** 2.8.0
### Expected Behavior

When consuming `ember-let` as a dependency in an addon, the addon should build successfully.
### Actual Behavior

When running `ember s` or `ember build`, the build fails and throws the following error:

``` sh
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at posixSplitPath (path.js:411:27)
    at Object.posix.basename (path.js:552:11)
    at Function.Module._resolveLookupPaths (module.js:247:37)
    at Function.Module._resolveFilename (module.js:316:31)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Project.emberCLIVersion (/Users/cf_frontside/app/node_modules/ember-cli/lib/utilities/version-utils.js:10:20)
    at getEmberCLIVersion (/Users/cf_frontside/app/node_modules/ember-cli-version-checker/index.js:12:31)
    at DependencyVersionChecker.EmberCLIDependencyVersionChecker (/Users/cf_frontside/app/node_modules/ember-cli-version-checker/index.js:115:19)
    at Function.deprecatedIsAbove [as isAbove] (/Users/cf_frontside/app/node_modules/ember-cli-version-checker/index.js:122:27)
    at CoreObject.module.exports.shouldSetupRegistryInIncluded (/Users/cf_frontside/app/node_modules/ember-cli-babel/index.js:13:21)
```
### Steps To Reproduce:
1. run `ember addon some-thing` to produce a fresh addon
2. Run `ember install ember-let`
3. Move the `ember-let` dependency from `devDependencies` to `dependencies`
4. run `ember s`

**Comment by cafreeman** [comment]
As a follow-up, I was able to get the add-on to build successfully by removing all uses/mentions of `ember-cli-version-checker` from `ember-let` and `npm link`ing it into my addon, so the issue appears to be originating in the version checker itself.

**Comment by Robdel12** [comment]
Looks like this was fixed with #25

**Comment by rwjblue** [comment]
Aha! That makes much more sense now!

**Comment by cafreeman** [comment]
Yep! Just cut a new release to incorporate the bogus super fix and am now successfully consuming ember-let in an addon :)

Gonna go ahead and close.
