### ISSUE TITLE
TypeError: Invalid Version: undefined

### ISSUE THREAD

**Issue by ming-codes** [thefrontside/ember-let#41]
I'm not sure if this is an issue with `ember-let` or `ember-cli-version-checker`.

Here's the stack trace.

```
Invalid Version: undefined
TypeError: Invalid Version: undefined
    at new SemVer (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:281:11)
    at compare (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:571:10)
    at Function.lt (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/node_modules/semver/semver.js:605:10)
    at DependencyVersionChecker.(anonymous function) [as lt] (/Users/mingliu/Workspace/prime/node_modules/ember-cli-version-checker/index.js:72:26)
    at Class.setupPreprocessorRegistry (/Users/mingliu/Workspace/prime/node_modules/ember-let/index.js:12:39)
```

I think the issue stem from ember moved bower package to npm. So when `checker.for('ember', 'bower').lt('2.0.0')` tries to check for it, it throws because it expects the bower package.

**Comment by Robdel12** [comment]
Hey @ming-codes, thanks for the report. Is this something you're still seeing? (I hope not, it took forever for us to reply 😳)
